config/routes.rb
Rails.application.routes.draw do
  get 'electrovalvulas/tres_vias'
  get 'electrovalvulas/servomando'
  get 'electrovalvulas/alta_presion'
  get 'electrovalvulas/mando_combinado'
  get 'electrovalvulas/mando_directo'
  get 'electrovalvulas/ferti_irrigacion'
  resources :products
  get 'store/presostatos'
  get 'store/componentes_de_automatizacion'
  get 'store/electrovalvulas'
  get 'store/electrovalvulas/mando_directo'
  get 'store/electrovalvulas/mando_combinado'
  get 'store/electrovalvulas/tres_vias'
  get 'store/electrovalvulas/ferti_irrigacion'
  get 'store/electrovalvulas/alta_presion'
  get 'store/electrovalvulas/servomando'
  get 'store/valvulas_neumaticas'
  get 'store/valvulas_membrana'
  get 'store/bridas'
  get 'store/index'
  root 'landing#home'
  get 'landing/about'
  get 'landing/policy'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/electrovalvulas_controller.rb
class ElectrovalvulasController < ApplicationController
  def tres_vias
  end

  def servomando
  end

  def alta_presion
  end

  def mando_combinado
  end

  def mando_directo
  end

  def ferti_irrigacion
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def home
  end



  def policy
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @valvesTags = [presostatos,componentes_de_automatizacion]
    @Presostatos = presostatos
    @Componentes_de_automatizacion=componentes_de_automatizacion
  end
  
  def presostatos


  end

  def componentes_de_automatizacion

  end
  def electrovalvulas

  end
  def valvulas_neumaticas
  end
  def valvulas_membrana

  end
  def bridas

  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/electrovalvulas_helper.rb
module ElectrovalvulasHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/valves_helper.rb
module ValvesHelper
end

app/views/electrovalvulas/ferti_irrigacion.html.erb
<div class="p-5 m-5  min-h-screen flex flex-col gap-5">
    <h1 class="text-5xl font-bold mb-5">
        Válvulas neumáticas
    </h1>
    <div class="bg-slate-100 shadow-xl w-[100%] h-[500px] rounded-xl flex">
        <%= image_tag("valves/electrovalvulas/ferti-irrigacion/222C-3.jpg", class:"w-[500px] h-[500px] rounded-l-xl object-cover")%>
        <div class="m-5">
            <h1 class="font-bold text-5xl">
                Válvulas con actuador Neumático 2 Vías - NC y NA
            </h1>

            <ul class="list-disc ml-8 mt-5">
                <li>
                    <b>
                        Electroválvulas en acero inoxidable AISI 316
                    </b>
                </li>
                <li>
                    <b>
                        Función:
                    </b>
                      NC
                </li>
                <li>
                    <b>
                        Roscas:
                    </b>
                      1/4" - 3/8" - 1/2"
                </li>

            </ul>


        </div>
    </div>

</div>

app/views/electrovalvulas/mando_combinado.html.erb
<div class="p-5 m-5  min-h-screen flex flex-col gap-5">
    <h1 class="text-5xl font-bold mb-5">
        
        Electroválvula Mando Combinado

    </h1>
    <div class="bg-slate-100 shadow-xl w-full h-[500px] rounded-xl flex">
        <%= image_tag("valves/electrovalvulas/mando-combinado/1.png", class:"w-[550px]  h-[500px] rounded-l-xl object-cover")%>
        <div class="m-5">
            <h1 class="font-bold text-4xl">
                Electroválvula Mando Combinado
            </h1>

            <div class="flex justify-end w-full items-end h-[200px] mt-52">
                <button class=" bg-blue-500 text-neutral-50 rounded-lg p-3 font-bold ">
                    <%= link_to "Download PDF file", "/PDF_files/electrovalvulas/mando-combinado/val.pdf",target: "_blank" %>
                </button>
            </div>
        </div>
    </div>


   
</div>

app/views/electrovalvulas/mando_directo.html.erb
<div class="p-5 m-5  min-h-screen flex flex-col gap-5">
    <h1 class="text-5xl font-bold mb-5">
        Mando Directo
    </h1>
    <div class="bg-slate-100 shadow-xl w-[100%] h-[500px] rounded-xl flex">
        <%= image_tag("valves/electrovalvulas/mando-directo/012C.jpg", class:"w-[300px]  h-[500px] rounded-l-xl object-cover")%>
        <div class="m-5">
            <h1 class="font-bold text-4xl">
                ELECTROVALVULAS 1/8" - 1/4" - Mando Directo 2 Vías - Normalmente Cerrada
            </h1>

            <ul class="list-disc ml-8 mt-5">
                <li>
                    <b>
                        Tamaños de Rosca:
                    </b>
                         1/8" - 1/4"
                </li>
                <li>
                    <b>
                        Tipos de Rosca:
                    </b>
                         G - BSP - NPT
                </li>
                <li>
                    <b>
                        Cuerpo: Latón o
                    </b>
                         Acero Inoxidable
                </li>
                <li>
                    <b>
                        Juntas: NBR (Opcional
                    </b>
                         FKM)
                </li>
                <li>
                    <b>
                        Piezas Internas: Acero
                    </b>
                         Inoxidable
                </li>

            </ul>
                <div class="flex justify-end w-full items-end h-[200px]">
                    <button class=" bg-blue-500 text-neutral-50 rounded-lg p-3 font-bold ">
                        <%= link_to "Download PDF file", "/PDF_files/electrovalvulas/mando-directo/012C.pdf",target: "_blank" %>
                    </button>
                </div>

        </div>
    </div>
    <div class="bg-slate-100 shadow-lg w-[100%] h-[500px] rounded-xl flex">
        <%= image_tag("valves/electrovalvulas/mando-directo/222C-3.jpg", class:"w-[300px] h-[500px] rounded-l-xl object-cover")%>
        <div class="m-5">
            <h1 class="font-bold text-4xl">
                ELECTROVALVULAS 1/8" - 1/4" - 3/8" - 1/2" 2 Vías - Normalmente Cerrada
            </h1>
            <ul class="list-disc ml-8 mt-5">
                <li>
                    <b>Tamaños de Rosca:</b>
                     1/8" - 1/4" - 3/8" - 1/2"
                </li>
                <li>
                    <b>Tipos de Rosca:</b>
                     G - BSP - NPT
                </li>
                <li>
                    <b>Cuerpo:</b>
                     Latón o Acero Inoxidable
                </li>
                <li>
                    <b>Juntas:</b>
                     NBR (Opcional FKM - PTFE)
                </li>
                <li>
                    <b>Piezas Internas:</b>
                     Acero Inoxidable
                </li>
            </ul>
                <div class="flex justify-end w-full items-end h-[200px]">
                    <button class=" bg-blue-500 text-neutral-50 rounded-lg p-3 font-bold ">
                        <%= link_to "Download PDF file", "/PDF_files/electrovalvulas/mando-directo/212C.pdf",target: "_blank" %>
                    </button>
                </div>

        </div>
    </div>
    <div class="bg-slate-100 shadow-lg w-[100%] h-[500px] rounded-xl flex">
        <%= image_tag("valves/electrovalvulas/mando-directo/442C.jpg", class:"w-[300px] h-[500px] rounded-l-xl object-cover")%>
        <div class="m-5">
            <h1 class="font-bold text-4xl">
                ELECTROVALVULAS 1/4" - 3/8" - 1/2" ALTA PRESIÓN 2 Vías - Normalmente Cerrada
            </h1>
            <ul class="list-disc ml-8 mt-5">
                <li>
                    <b>
                        Tamaños de Rosca:     
                    </b>
                    1/8" - 1/4" - 3/8" - 1/2"
                </li>
                <li>
                    <b>
                        Tipos de Rosca:    
                    </b>
                    G - BSP - NPT
                </li>
                <li>
                    <b>
                        Cuerpo:     
                    </b>
                    Latón o Acero Inoxidable
                </li>
                <li>
                    <b>
                        Juntas:     
                    </b>
                    NBR (Opcional FKM - PTFE)
                </li>
                <li>
                    <b>
                        Piezas Internas:    
                    </b>
                    Acero Inoxidable
                </li>
            </ul>
                <div class="flex justify-end w-full items-end h-[200px]">
                    <button class=" bg-blue-500 text-neutral-50 rounded-lg p-3 font-bold ">
                        <%= link_to "Download PDF file", "/PDF_files/electrovalvulas/mando-directo/422C.pdf",target: "_blank" %>
                    </button>
                </div>

        </div>
    </div>
    <div class="bg-slate-100 shadow-lg w-[100%] h-[500px] rounded-xl flex">
        <%= image_tag("valves/electrovalvulas/mando-directo/212A-3.jpg", class:"w-[300px] h-[500px] rounded-l-xl object-cover")%>
        <div class="m-5">
            <h1 class="font-bold text-4xl">
                ELECTROVALVULAS 1/8" y 1/4" - Mando Directo 2 Vías - Normalmente Abierta
            </h1>

            <ul class="list-disc ml-8 mt-5">
                <li>
                    <b>Tamaños de Rosca:</b>
                     1/8"
                </li>
                <li>
                    <b>Tipos de Rosca:</b>
                     G - BSP
                </li>
                <li>
                    <b>Cuerpo:</b>
                     Latón
                </li>
                <li>
                    <b>Juntas:</b>
                     NBR (Opcional FKM)
                </li>
                <li>
                    <b>Piezas Internas:</b>
                     Acero Inoxidable
                </li>
            </ul>
                <div class="flex justify-end w-full items-end h-[200px]">
                    <button class=" bg-blue-500 text-neutral-50 rounded-lg p-3 font-bold ">
                        <%= link_to "Download PDF file", "/PDF_files/electrovalvulas/mando-directo/212A.pdf",target: "_blank" %>
                    </button>
                </div>

        </div>
    </div>
</div>

app/views/landing/home.html.erb
<div class="snap-x snap-mandatory  pb-10">
    <div class="grid grid-rows-2 grid-cols-7 min-w-screen bg-blue-100 snap-always">
    <div class="col-span-5 w-full">
        <%= image_tag("marketing/valve-2.jpg", class:"h-[600px] w-full object-cover border-y-4 border-l-4 border-slate-100 ")%>

        <h1 class="titleAnimate absolute top-[200px] left-[20px] font-extrabold text-7xl">
            Bienvenido a <span class="text-blue-500 bg-slate-100 p-3 rounded-lg">Delta.</span>
        </h1>

        <%= link_to "Visita nuestro catálogo", store_index_path ,class:"absolute top-[300px] p-5 font-semibold bg-blue-100 ml-[32px]  min-w-[100px] 
        rounded-xl hover:bg-slate-900 hover:text-slate-50 transition-all duration-300"%> 
    </div>
    <div class="col-span-2 w-full">
    <%= image_tag("marketing/valve-1.jpg", class:"h-[600px] bg-green-500 border-4 border-slate-100 w-full object-cover")%>
    </div>
    <div class="w-full col-span-7">
        <%= image_tag("marketing/valve-3.jpg", class:"h-[600px] w-full bg-green-500 border-4 border-t-0 border-slate-100 col-span-7 object-cover")%>

    </div>

    </div>
    <div class="p-10 snap-always">
        <h1 class="font-bold ml-2 text-7xl lg:text-left text-center">
            ¿Qué es ITD?
        </h1>
        <h2 class="flex justify-center my-8 w-[900px] bg-slate-200 bg-opacity-90
            rounded-lg text-left p-3 font-medium text-blue-500 text-2xl">
            En ITD, S.L., estamos especializados en la 
            fabricación y suministro de válvulas
             para la automatización y conducción de todo tipo fluidos.
            Disponemos de departamentos de ingeniería y oficina técnica.
    
        </h2>
        <h1 class="font-bold ml-2 text-7xl lg:text-left text-center">
            ¿Qué servicio puede esperar con ITD?
        </h1>
        <div class="flex flex-col lg:flex-row">
            <ul class= "flex-grow grid grid-cols-3 list-blue-500 text-blue-500 mark-blue-500 ml-5 text-xl mt-10 flex flex-col gap-5">
                <li class="min-h-[100px] bg-blue-500 text-slate-100 p-5 rounded-lg ">
                    <span class="font-bold">
                        Departamento de Ingeniería,
                    </span>
                    para darle la mejor solución para cada proyecto concreto.
                </li>
                <li class="bg-blue-500 text-slate-100 p-5 rounded-lg col-span-2">
                    <span class="font-bold">
                        Oficina Técnica,
                    </span>
                    donde diseñamos válvulas y electroválvulas para todo tipo de aplicaciones o de acuerdo con los requerimientos de nuestros clientes.
                </li>
                <li class="min-h-[100px] bg-blue-500 text-slate-100 p-5 rounded-lg col-span-2 row-span-2">
                    <span class="font-bold">
                        Personal cualificado,
                    </span>
                    para apoyarle técnicamente en sus proyectos y determinar la válvula o componente más apropiado para cada aplicación concreta.
                </li>

                <li class="min-h-[100px] bg-blue-500 text-slate-100 p-5 rounded-lg row-span-2">
                    <span class="font-bold">
                        Control de calidad,
                    </span>
                    <span >
                        donde se verifican al 100% todas nuestras válvulas. Se realizan pruebas bajo presión, estanqueidad, ensayos eléctricos…
                    </span>
                </li>
                <li class="min-h-[100px] bg-blue-500 text-slate-100 p-5 rounded-lg col-span-3">
                    <span class="font-bold">
                        Experiencia,
                    </span>
                    <span class="text">
                        lo que garantiza el producto idóneo para cada aplicación concreta.
                    </span>
                </li>

            </ul>
            <div  class="text-black m-5 mt-10 text-2xl lg:text-right text-center">
                <p>
                    El apoyo técnico ofrecido por ITD, S.L. unido a la alta calidad del producto, siempre han sido nuestros puntos fuertes ya que nuestros clientes saben que cuentan con una solución fiable y segura para el buen y continuado funcionamiento de los equipos.
                </p>
                <p class="mt-5">
                    Le proponemos conocer nuestras ventajas y descubrir más sobre nuestros productos reconocidos por nivel calidad. Garantizamos no sólo una producción de primer nivel, sino también el suministro ágil y seguro de nuestros productos.
                </p>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_contact.html.erb
<div class="p-2 bg-blue-200 text-blue-500 z-50 font-semibold fixed bottom-0 w-screen h-[40px] text-center">
    Para comprar los productos puede contactarnos por email, 
    <span class="font-bold">
        delta@industrialdelta.com
    </span>
</div>

app/views/layouts/_footer.html.erb
<div class="bg-slate-900 text-white p-5 flex flex-col min-w-screen relative ">
    <%= link_to "Inicio", root_path, class:"hover:underline decoration-1"%>
    <%= link_to "Tienda", store_index_path  , class:"hover:underline decoration-1"%>
    <%= link_to "Aviso legal", landing_policy_path, class:"hover:underline decoration-1"%>
</div>

app/views/layouts/_header.html.erb
<div class=" h-[100px]  p-4  fixed top-0 w-screen bg-slate-200  
border-b-2 border-slate-100 border-opacity-30 bg-white z-50">
    <div class=" flex items-center w-full h-[100px] p-4 fixed top-0">
        <h3 class="font-bold text-3xl hover:cursor-pointer">
            <%= link_to "Delta.", root_path %>
        </h3>
        <div class="flex  justify-end p-4 font-semibold w-screen gap-14">
            <%= link_to "Inicio", root_path, class:"hover:underline decoration-2"%>
            <%= link_to "Catálogo", store_index_path, class:"hover:underline decoration-2"%>
            <%= link_to "Aviso legal y contacto", landing_policy_path, class:"hover:underline decoration-2"%>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Delta</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.tailwindcss.com"></script> 
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header"%>
    <div class="pt-[100px] h-screen ">

      <%= yield %>
    </div>
    <%= render "layouts/contact"%>

  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <p>
      <%= link_to "Show this product", product %>
    </p>
  <% end %>
</div>

<%= link_to "New product", new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>

app/views/store/electrovalvulas.html.erb
<div class="grid grid-row-flow justify-content grid-cols-1 lg:grid-cols-3 p-4 grid-rows-4 gap-5">


    <div class="w-[400px] bg-slate-100 h-[400px] border-slate-300 border-opacity-50 border-2 
        rounded-xl shadow-md shadow-slate-300  hover:cursor-pointer transition-all duration-300 
        hover:bg-blue-500 hover:shadow-slate-50 hover:text-slate-50">
        <%=link_to "",  electrovalvulas_mando_directo_path , class:" w-[400px] h-[400px] absolute"%>
        <%= image_tag("valves/electrovalvulas/mando-directo/442C.jpg", class:"object-cover w-full p-2 h-[300px] rounded-xl")%>

        <h1 class="text-3xl font-bold px-5 h-[90px]">
            Mando directo
        </h1>
                                        
    </div>
    <div class="w-[400px] bg-slate-100 h-[400px] border-slate-300 border-opacity-50 border-2 
        rounded-xl shadow-md shadow-slate-300  hover:cursor-pointer transition-all duration-300 
        hover:bg-blue-500 hover:shadow-slate-50 hover:text-slate-50">
        <%=link_to "", electrovalvulas_ferti_irrigacion_path, class:" w-[400px] h-[400px] absolute"%>
        <%= image_tag("valves/electrovalvulas/ferti-irrigacion/222C-3.jpg", class:"object-cover w-full p-2 h-[300px] rounded-xl")%>

        <h1 class="text-3xl font-bold px-5 h-[90px]">
            Ferti-Irrigación
        </h1>
                                        
    </div>
    
    <div class="w-[400px] bg-slate-100 h-[400px] border-slate-300 border-opacity-50 border-2 
        rounded-xl shadow-md shadow-slate-300  hover:cursor-pointer transition-all duration-300 
        hover:bg-blue-500 hover:shadow-slate-50 hover:text-slate-50">
        <%=link_to "", electrovalvulas_servomando_path, class:" w-[400px] h-[400px] absolute"%>
        <%= image_tag("valves/electrovalvulas/servomando/acero.jpg", class:"object-cover w-full p-2 h-[300px] rounded-xl")%>

        <h1 class="text-3xl font-bold px-5 h-[90px]">
            Servomando
        </h1>
                                        
    </div>

    <div class="w-[400px] bg-slate-100 h-[400px] border-slate-300 border-opacity-50 border-2 
        rounded-xl shadow-md shadow-slate-300  hover:cursor-pointer transition-all duration-300 
        hover:bg-blue-500 hover:shadow-slate-50 hover:text-slate-50">
        <%=link_to "", electrovalvulas_tres_vias_path, class:" w-[400px] h-[400px] absolute"%>
        <%= image_tag("valves/electrovalvulas/3-vias/223C-3.jpg", class:"object-cover w-full p-2 h-[300px] rounded-xl")%>

        <h1 class="text-3xl font-bold px-5 h-[90px]">
            3 Vías
        </h1>
                                        
    </div>

    <div class="w-[400px] bg-slate-100 h-[400px] border-slate-300 border-opacity-50 border-2 
        rounded-xl shadow-md shadow-slate-300  hover:cursor-pointer transition-all duration-300 
        hover:bg-blue-500 hover:shadow-slate-50 hover:text-slate-50">
        <%=link_to "", electrovalvulas_mando_combinado_path, class:" w-[400px] h-[400px] absolute"%>
        <%= image_tag("valves/electrovalvulas/mando-combinado/1.png", class:"object-cover w-full p-2 h-[300px] rounded-xl")%>

        <h1 class="text-3xl font-bold px-5 h-[90px]">
            Mando Combinado
        </h1>
                                        
    </div>
        
</div>

app/views/store/index.html.erb
<div class="grid grid-row-flow   space-around lg:justify-start grid-cols-1 md:grid-cols-2 lg:grid-cols-3 p-4 grid-rows-2  gap-5">
    <div class="  w-[400px] bg-slate-100 h-[400px] border-slate-300 border-opacity-50 border-2 
        rounded-xl shadow-md shadow-slate-300  hover:cursor-pointer transition-all duration-300 
        hover:bg-blue-500 hover:shadow-slate-50 hover:text-slate-50">
        <%=link_to "", store_presostatos_path, class:" w-[400px] h-[400px] absolute"%>
        <%= image_tag("valves/presostatos/620.jpg", class:"object-cover w-full p-2 h-[300px] rounded-xl")%>

        <h1 class="text-3xl font-bold px-5 h-[90px]">
            Presostatos
        </h1>
                                        
    </div>
    <div class="  w-[400px] bg-slate-100 h-[400px] border-slate-300 border-opacity-50 border-2 
        rounded-xl shadow-md shadow-slate-300  hover:cursor-pointer transition-all duration-100 
        hover:bg-blue-500 hover:shadow-slate-50 hover:text-slate-50">
        <%=link_to "", store_componentes_de_automatizacion_path, class:" w-[400px] h-[400px] absolute"%>
        <%= image_tag("valves/componentes/com.jpg", class:"object-cover w-full p-2 h-[300px] rounded-xl")%>

        <h1 class="text-3xl font-bold px-5 h-[90px]">
            Componentes de automatización
        </h1>
                                        
    </div>
    <div class="  w-[400px] bg-slate-100 h-[400px] border-slate-300 border-opacity-50 border-2 
        rounded-xl shadow-md shadow-slate-300  hover:cursor-pointer transition-all duration-300 
        hover:bg-blue-500 hover:shadow-slate-50 hover:text-slate-50">
        <%=link_to "", store_valvulas_neumaticas_path, class:" w-[400px] h-[400px] absolute"%>
        <%= image_tag("valves/neumaticas/neu.jpg", class:"object-cover w-full p-2 h-[300px] rounded-xl")%>


        <h1 class="text-3xl font-bold px-5 h-[90px]">
            Válvulas Neumáticas
        </h1>
                                        
    </div>
    <div class="  w-[400px] bg-slate-100 h-[400px] border-slate-300 border-opacity-50 border-2 
        rounded-xl shadow-md shadow-slate-300  hover:cursor-pointer transition-all duration-300 
        hover:bg-blue-500 hover:shadow-slate-50 hover:text-slate-50">
        <%=link_to "", store_electrovalvulas_path, class:" w-[400px] h-[400px] absolute"%>
        <%= image_tag("valves/electrovalvulas/mando-directo/012C.jpg", class:"object-cover w-full p-2 h-[300px] rounded-xl")%>

        <h1 class="text-3xl font-bold px-5 h-[90px]">
            Electroválvulas
        </h1>
                                        
    </div>
    <div class="  w-[400px] bg-slate-100 h-[400px] border-slate-300 border-opacity-50 border-2 
        rounded-xl shadow-md shadow-slate-300  hover:cursor-pointer transition-all duration-300 
        hover:bg-blue-500 hover:shadow-slate-50 hover:text-slate-50">
        <%=link_to "", store_valvulas_membrana_path, class:" w-[400px] h-[400px] absolute"%>

        <%= image_tag("valves/membrana/val.png", class:"object-cover w-full p-2 h-[300px] rounded-xl")%>

        <h1 class="text-3xl font-bold px-5 h-[90px]">
            Válvulas de Membrana
        </h1>
                                        
    </div>

    <div class="  w-[400px] bg-slate-100 h-[400px] border-slate-300 border-opacity-50 border-2 
        rounded-xl shadow-md shadow-slate-300  hover:cursor-pointer transition-all duration-300 
        hover:bg-blue-500 hover:shadow-slate-50 hover:text-slate-50">
        <%=link_to "", store_bridas_path, class:" w-[400px] h-[400px] absolute"%>
        <%= image_tag("valves/bridas/1.jpg", class:"object-cover w-full p-2 h-[300px] rounded-xl")%>

        <h1 class="text-3xl font-bold px-5 h-[90px]">
            Bridas
        </h1>
                                        
    </div>

        
</div>